language: java

before_install:
  - unset TRAVIS
  - unset _JAVA_OPTIONS
  - wget http://www.deflaker.org/maven/apache-maven-3.5.0.zip
  - unzip -qq apache-maven-3.5.0.zip
  - export M2_HOME=$PWD/apache-maven-3.5.0
  - export PATH=$M2_HOME/bin:$PATH


install: true
#   - "mvn -P ${CONTAINER} -DJBOSS_REPO=true -DskipTests=true -B install"
script:
#   - "mvn -P ${CONTAINER} -DJBOSS_REPO=true test"
  - "mvn -P ${CONTAINER} -DJBOSS_REPO=true verify"
after_success:
  - "bash .travis-sonatype-deploy.sh"
jdk:
  - openjdk8
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ce8c97d4907f0681aa48
    on_success: change
    on_failure: always
    on_start: never
env:
  global:
    - CONTAINER=wildfly-managed
    - secure: "OnYfX1bWd1nt4lU6fGEtiWc/AqNwac32YQEm8AdPaU83zOZGe2yyBOLX+fTxqp7CUPpbJM0kLCQzDTrurwXJNtd9D8b8C5rWBvvNS7tloVlwCMbfSiSXpJZK6bygGo0puQcnFtaivtmGD6DRZQWgbVKNdJf5iW/X+46k+nOZqtg="
    - secure: "mjX857IwiXKts1ZWrKDVQOQpkFN+vUrPmQNneYim4dVN+McXOiyyvM/iYgH14E2FFHlWe/1fHLU59Wf34r7K7T+cd8J79D78u6dIljHmxucMu5+O7giexzkvEqTXafAQQrLSan0iUnU3dgcYbqaZ9Fz5ZRjC7gLF48mRUsf+lIc="
    - FIREBASE_KEY=AIzaSyDU7I6pnN322BvRNN24jRX52owAvuHH1K4
